### ISSUE TITLE
Does the auxiliary_model  share the parameters with the Primary model?

### ISSUE THREAD

**Issue by raozhongyu** [AvivNavon/AuxiLearn#6]
Thanks for your great work. I would like to use the metaoptimizer on my own model. I'd like to konw  does the auxiliary_model  share the parameters with the Primary model?

**Comment by AvivNavon** [comment]
Hi @raozhongyu 
No, we do not share parameters between auxiliary and primary networks.

**Comment by raozhongyu** [comment]
I get it. Thanks a lot.



---Original---
From: "Aviv ***@***.***&gt;
Date: Mon, Feb 27, 2023 20:39 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [AvivNavon/AuxiLearn] Does the auxiliary_model  share theparameters with the Primary model? (Issue #6)




 
Hi @raozhongyu
 No, we do not share parameters between auxiliary and primary networks.

**Comment by raozhongyu** [comment]
Hi, I  meet some problem that the dloss_train_dparams and dlloss_val_dparams is None. Could you give me some suggestions?

**Comment by raozhongyu** [comment]
Hi I sovle this question. But I meet another question  during the  _approx_inverse_hvp :
RuntimeError: derivative for aten::grid_sampler_2d_backward is not implemented
terminate called without an active exception
Fatal Python error: Aborted
 Could you give me some suggestions?

**Comment by AvivNavon** [comment]
Hi, this seems like an issue with `grid_sampler_2d_backward`. Please refer to: https://github.com/pytorch/pytorch/issues/34704

**Comment by raozhongyu** [comment]
Thanks a lot.
